### ISSUE TITLE
please make this work in Plone 5 :)

### ISSUE THREAD

**Issue by tkimnguyen** [collective/uwosh.snippets#10]

**Comment by rileydog** [comment]
in 5.1, snippets appears to generate error (even after uninstalling it)
================
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in __call__
  Module plone.z3cform.layout, line 50, in update
  Module plone.dexterity.browser.add, line 130, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module plone.dexterity.browser.add, line 105, in handleAdd
  Module z3c.form.form, line 265, in createAndAdd
  Module plone.dexterity.browser.add, line 80, in add
  Module plone.dexterity.utils, line 182, in addContentToContainer
  Module Products.BTreeFolder2.BTreeFolder2, line 461, in _setObject
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module uwosh.snippets.linkintegrity, line 132, in modifiedDexterity
  Module uwosh.snippets.linkintegrity, line 85, in checkSnippetReferences
  Module lxml.html, line 867, in fromstring
  Module lxml.html, line 755, in document_fromstring
ParserError: Document is empty

**Comment by tkimnguyen** [comment]
ok to be fair, I meant 5.0, and @obct537 did that work in https://github.com/collective/uwosh.snippets/commit/3e125232152d10c8735bc93814c1f0d1b1bdada8 last year

We haven't tried this with 5.1 yet. Going to close this issue and re-file your stack trace under a new title.
