### ISSUE TITLE
Some detail missing in a how-to

### ISSUE THREAD

**Issue by dbitouze** [collective/uwosh.snippets#15]
On http://www.uwosh.edu/ploneprojects/docs/how-tos/how-to-embed-video-on-a-page, in the "Directions" → "Create a Snippet"→ 1st item, it is said:

> "Activate "Snippets" (activating this product will create a folder called ".snippets" on the root level of your site.

But that's wrong: one has to use the ZMI to rename the folder to have the "." (and the closing parenthesis is missing).

BTW, could much nicer if the ZMI could be avoided.

**Comment by tkimnguyen** [comment]
That site is old and I don't maintain it anymore. However, I will contact the current maintainer to remove that or update it. The instructions on how to use snippets should be moved to the documentation of the package, here.

**Comment by tkimnguyen** [comment]
If you look at http://www.uwosh.edu/ploneprojects/docs/how-tos/how-to-embed-video-on-a-page you'll see the publication date is Dec. 2014, and the current Plone 5 compatible snippets is from July 2016.

**Comment by tkimnguyen** [comment]
@bledwell is the site maintainer and author of that how-to... he is fixing it at the moment :)

**Comment by bledwell** [comment]
@dbitouze Thankyou for the update! I added some additional detail to that "how to" as to the version number were using which is terribly old. "UPDATE: This solution works for an older version of the "Snippets" product. This solution is for version 0.9.27"
http://www.uwosh.edu/ploneprojects/docs/how-tos/how-to-embed-video-on-a-page

**Comment by dbitouze** [comment]
@bledwell  You're welcome! :)
