### ISSUE TITLE
Relation with tiles?

### ISSUE THREAD

**Issue by gforcada** [collective/uwosh.snippets#5]
Future Plone versions (5.x or 6 or ...) will eventually have the whole tiles machinery (plone.app.blocks, plone.tiles, plone.app.standardtiles and plone.app.mosaic, probably something else more).

Still there would be use cases for this snippets distribution: what if within the rich text editor I want to place an image (from plone.app.contentypes or a custom image content type)?

The placeholders approach still makes sense, as you want the whole text to be a single thing (maybe a single tile) but within the text you want to plug some content on it.

So do you see a path where placeholders would actually save a tile reference within the rich text that then will be later processed?

**Comment by tkimnguyen** [comment]
(figured this was an old discussion so was ok to close)
